name: PR MacOS
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build project
        run: |
          xcodebuild -scheme CatalanitzadorPerAlMac -project CatalanitzadorPerAlMac.xcodeproj -sdk macosx -configuration Debug build | xcpretty
